apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: cbioportal-spring-boot
  name: cbioportal-spring-boot
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/cbioportal-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cbioportal-spring-boot
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cbioportal-spring-boot
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cbioportal-public
        image: cbioportal/cbioportal:release-1.15.0-rc2
        command: ["/usr/bin/java", 
                  "-Xms2g",
                  "-Xmx6g",
                  "-Xss20m",
                  "-XX:PermSize=128m",
                  "-Ddbconnector=dbcp",
                  "-Dsession.service.url=http://cbioportal-session-service/api/sessions/public_portal/",
                  "-jar",
                  "/webapp-runner.jar",
                  "--enable-compression",
                  "--port",
                  "8888",
                  "--expand-war",
                  "/app.war"]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /api/swagger-ui.html
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 5
        name: cbioportal-spring-boot
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
            requests:
                cpu: 250m
                memory: 6Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
