apiVersion: v1
kind: Service
metadata:
  labels:
    run: cbioportal-spring-boot
  name: cbioportal
  selfLink: /api/v1/namespaces/default/services/cbioportal-spring-boot
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    run: cbioportal-spring-boot
  type: ClusterIP