apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2019-11-19T14:49:29Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: genome-nexus
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2019-09-26
  machineType: t3.xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: genome-nexus
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-10-24T21:18:37Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: large-mem
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: r5.xlarge
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: large-mem
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-06T18:29:31Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2018-08-06T18:29:31Z"
  labels:
    kops.k8s.io/cluster: cbioportal.review.k8s.local
  name: nodes
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: t2.medium
  maxSize: 4
  minSize: 4
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
  - us-east-1c
