apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genie-gn-mongo-pvc
  namespace: genome-nexus
spec:
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 50Gi # volume size requested
