apiVersion: v1
kind: Service
metadata:
  labels:
    run: cbioportal-session-service
  name: cbioportal-session-service
  selfLink: /api/v1/namespaces/default/services/cbioportal-session-service
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    run: cbioportal-session-service
  type: ClusterIP