apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: cbioportal-session-service
  name: cbioportal-session-service
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/cbioportal-session-service
spec:
  replicas: 2
  selector:
    matchLabels:
      run: cbioportal-session-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cbioportal-session-service
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8888"
        - name: MONGODB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: cbioportal-session-service-mongo-mongodb
              key: mongodb-root-password
        image: cbioportal/session-service:e5bfa43e883f33d730cf0bb460912f31c86d1977
        command: ["/usr/bin/java", 
                  "-Dspring.data.mongodb.uri=mongodb://root:${MONGODB_ROOT_PASSWORD}@cbioportal-session-service-mongo-mongodb:27017/session_service?authSource=admin",
                  "-jar",
                  "/app.war"]
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 5
        name: cbioportal-session-service
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}