prometheus:
  serviceMonitors:
    - name: nginx-ingress-service-monitor
      jobLabel: nginx-ingress
      selector:
        matchLabels:
          app: nginx-ingress
          release: eating-dingo
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: metrics
          interval: 30s
    - name: cbioportal-production-db-mysql-service-monitor
      jobLabel: cbioportal-production-db-mysql
      selector:
        matchLabels:
          app: cbioportal-production-db-mysql
          release: cbioportal-production-db
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: metrics
          interval: 30s
