prometheus:
  retention: 7d
  serviceMonitors:
    - name: nginx-ingress-service-monitor
      jobLabel: nginx-ingress
      selector:
        matchLabels:
          app: nginx-ingress
          release: eating-dingo
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: metrics
          interval: 30s
