prometheus:
  serviceMonitors:
    - name: nginx-ingress-service-monitor
      jobLabel: nginx-ingress
      selector:
        matchLabels:
          app: nginx-ingress
          release: eating-dingo
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: metrics
          interval: 30s
  serviceMonitorsSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - gn-spring-boot
      - alertmanager
      - exporter-coredns
      - exporter-kube-controller-manager
      - exporter-kube-dns
      - exporter-kube-etcd
      - exporter-kube-scheduler
      - exporter-kube-state
      - exporter-kubelets
      - exporter-kubernetes
      - exporter-node
      - grafana
      - prometheus
      - prometheus-operator
