prometheus:
  additionalServiceMonitors:
    - name: nginx-ingress-service-monitor
      jobLabel: nginx-ingress
      selector:
        matchLabels:
          app: nginx-ingress
      namespaceSelector:
        matchNames:
          - default
      endpoints:
        - port: metrics
          interval: 30s
        - port: stats
          interval: 30s
  prometheusSpec:
    retention: 10d
    # aws specific storage class
    storageSpec:
      storageClassName: gp2
      resources:
        requests:
          storage: 40Gi
grafana:
  plugins:
    - grafana-worldmap-panel
