apiVersion: v1
kind: Service
metadata:
  name: oncokb-sop
  namespace: oncokb
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ExternalName
  externalName: www.oncokb.org/content/files/OncoKB_Curation_Protocol_v1.0.pdf
