apiVersion: v1
kind: Service
metadata:
  labels:
    run: oncokb-sop
  name: oncokb-sop
  namespace: oncokb
  type: ExternalName
  externalName: https://www.oncokb.org/content/files/OncoKB_Curation_Protocol_v1.0.pdf
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: oncokb-sop
  type: ClusterIP
