apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: gn-genie
  name: gn-genie
  selfLink: /apis/extensions/v1beta1/namespaces/genome-nexus/deployments/gn-genie
spec:
  replicas: 2
  selector:
    matchLabels:
      run: gn-genie
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gn-genie
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8888"
        - name: MONGODB_URI
          value: mongodb://gn-mongo-v0dot9-genie-mongodb:27017/annotator?connectTimeoutMS=120000
        image: genomenexus/gn-spring-boot:v1.0.0-263-g387164e
        imagePullPolicy: Always
        command: [ "java" ]
        args: [
            "-Dspring.data.mongodb.uri=$(MONGODB_URI)",
            # this is to use VEP running inside K8s. Remove to use
            # grch37.rest.ensembl.org instead
            "-Dgn_vep.region.url=http://gn-vep/vep/human/region/VARIANT",
            "-jar",
            "/app.war"
        ]
        readinessProbe:
          httpGet:
            path: /ensembl/canonical-transcript/hgnc/tp53?isoformOverrideSource=uniprot
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 5
        name: gn-genie
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          requests:
              memory: 1.5Gi
          limits:
              memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # run on genome nexus machines
      nodeSelector:
         kops.k8s.io/instancegroup: genome-nexus
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: gn-genie
    app: gn-genie
  name: genome-nexus-genie
  selfLink: /api/v1/namespaces/genome-nexus/services/genome-nexus-genie
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  - port: 443
    name: https
    targetPort: 8888
  selector:
    run: gn-genie
  type: ClusterIP
