apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: gn-spring-boot
  name: gn-spring-boot
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gn-spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      run: gn-spring-boot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gn-spring-boot
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8888"
        - name: MONGODB_URI
          value: mongodb://gn-mongo-v0dot3-mongodb:27017/annotator?connectTimeoutMS=120000
        - name: SENTRY_DSN
          valueFrom: 
            secretKeyRef:
              name: genome-nexus-sentry-dsn
              key: dsn
        image: genomenexus/gn-spring-boot:v1.0.0-110-g7538a5d
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /ensembl/canonical-transcript/hgnc/tp53?isoformOverrideSource=uniprot
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 5
        name: gn-spring-boot
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
