apiVersion: v1
kind: Service
metadata:
  labels:
    run: gn-spring-boot
    app: gn-spring-boot
  name: genome-nexus
  selfLink: /api/v1/namespaces/default/services/genome-nexus
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: genomenexus.cbioportal.review.
    # # Note that the backend talks over HTTP.
    # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # # TODO: Fill in with the ARN of your certificate.
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:070278699608:certificate/fe976eb4-534a-470a-ab11-d292a57fc4a3
    # # Only run SSL on the port named "https" below.
    # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    # # default is 1m, but gives 504 gateway errors when querying many mutations
    # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: 300
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  - port: 443
    name: https
    targetPort: 8888
  selector:
    run: gn-spring-boot
  type: ClusterIP
