apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: genome-nexus-v2-cert
spec:
  secretName: genome-nexus-v2-cert
  dnsNames:
  - v2.genomenexus.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - v2.genomenexus.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cbioportal-k8s-cert
spec:
  secretName: cbioportal-k8s-cert
  dnsNames:
  - k8s.cbioportal.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - k8s.cbioportal.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer