apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: null
  generation: 1
  labels:
    run: gn-vep
  name: gn-vep
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gn-vep
spec:
  replicas: 2
  selector:
    matchLabels:
      run: gn-vep
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: gn-vep
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8888"
        image: genomenexus/gn-vep:fed3ac3ad9305fff37d09c171ab2855f81bb4182
        imagePullPolicy: Always
        volumeMounts:
        - name: vep-data
          subPath: cache
          mountPath: /opt/vep/.vep
        readinessProbe:
          httpGet:
            path: /vep/human/region/7:140453136-140453136:1/T
            port: 8888
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /vep/human/region/7:140453136-140453136:1/T
            port: 8888
          initialDelaySeconds: 30
          timeoutSeconds: 6
          periodSeconds: 15
        name: gn-vep
        ports:
        - containerPort: 8888
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      # download data from s3 bucket (takes ~40m).
      # TODO: It might be better to create a volume from an existing snapshot.
      initContainers:
      - name: download-vep-cache
        image: busybox
        command: ['sh', '-c',
			'cd /vep_data; wget https://gn-vep-data.s3.amazonaws.com/file_list.txt; for f in $(cat file_list.txt); do mkdir -p $(dirname $f); wget https://gn-vep-data.s3.amazonaws.com/$f -O $f; done; cd cache; tar xvzf homo_sapiens_vep_92_GRCh37.tar.gz'
        ]
        volumeMounts:
        - name: vep-data
          mountPath: /vep_data
      volumes:
      - name: vep-data
        emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: gn-vep
    app: gn-vep
  name: gn-vep
  selfLink: /api/v1/namespaces/default/services/gn-vep
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8888
  - port: 443
    name: https
    targetPort: 8888
  selector:
    run: gn-vep
  type: ClusterIP
